### ISSUE TITLE
Microverse-Portfolio

### ISSUE THREAD

**Issue by Theodore354** [AkshithaReddy1899/Microverse-Portfolio#11]
Good job done so far!
**To Highlight**

- Linters are working properly 👍 
- Proper use of github workflow 👍 
- page is responsive 👍
- Code looks clean. 👍
I think you are ready to move to the next step .Congratulations 💯 
![review](https://user-images.githubusercontent.com/55790589/145534269-63550212-6bd9-4054-a78c-f4a7ce02e461.jpg)

**Comment by mrparkersson** [comment]
Congratulations @AkshithaReddy1899 good job done so far!!

**Comment by jaflih** [comment]
You've done a really nice job so far 👍 💯 🥇 

Your design is really good, just please compare your design and the template design and try to have the same as possible.

**Your template** 
<img width="1233" alt="Capture d’écran 2021-12-10 à 08 26 29" src="https://user-images.githubusercontent.com/7243132/145534729-4edccbbb-c0c1-42fd-ac9f-27890053845e.png">
<img width="1102" alt="Capture d’écran 2021-12-10 à 08 26 15" src="https://user-images.githubusercontent.com/7243132/145534792-e68fdf90-45e6-4576-827b-33bc3d05d9da.png">

**Figma template**

<img width="507" alt="Capture d’écran 2021-12-10 à 08 28 16" src="https://user-images.githubusercontent.com/7243132/145534846-ca208076-0764-4051-86b2-e881e318e378.png">
<img width="507" alt="Capture d’écran 2021-12-10 à 08 28 10" src="https://user-images.githubusercontent.com/7243132/145534856-a97059e8-55d2-4ab1-9597-c5946e00b6e9.png">

**Comment by AkshithaReddy1899** [comment]
Thank you for your kind words, @Theodore354, @mrparkersson, @jihaneH. I will fix the design as soon as possible.
