### ISSUE TITLE
mornig session code review

### ISSUE THREAD

**Issue by mugishasam123** [AkshithaReddy1899/Microverse-Portfolio#15]
hey @AkshithaReddy1899 ✋ 

congratulations on the work you did so far but they are still a few issues you still need to work on 👍 

- [ ] please try to match exactly with Figma design 💯 
- [ ] on line 365 in index.html kindly put descriptive alternative image text.

- [ ] hope to hear from you when issues are resolved ❤️

**Comment by AkshithaReddy1899** [comment]
Sure, I will work on the issues as soon as possible.
